module CodecLZO

export
    LZOCompressor,
    LZOCompressorStream,
    LZODecompressor,
    LZODecompressorStream

import TranscodingStreams:
    TranscodingStreams,
    TranscodingStream,
    Memory,
    Error,
    initialize,
    finalize,
    splitkwargs

using LZO_jll

# Module containing directly wrapped ccalls generated by CLang.jl
#include("Liblzo2_clang.jl")
# Library functions that have a Julian interface. This file originally preceded the above module
include("liblzo2.jl")
include("compression.jl")
include("decompression.jl")

end
